# Generated by Django 4.2 on 2024-06-06 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Name', models.CharField(blank=True, max_length=35, verbose_name='Nombres')),
                ('LastName', models.CharField(blank=True, max_length=35, verbose_name='Apellido P')),
                ('MiddleName', models.CharField(blank=True, max_length=35, verbose_name='Apellido M')),
                ('Curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('ocupation', models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Director'), ('2', 'Supervisor'), ('3', 'Profesor'), ('4', 'Asesor'), ('5', 'Alumno'), ('6', 'Tutor')], max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('CP', models.PositiveIntegerField(default=0, verbose_name='Codigo postal')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('URL', models.CharField(max_length=50, verbose_name='Usuario')),
                ('description', models.TextField(blank=True, verbose_name='descripcion del producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('User', models.CharField(max_length=50, verbose_name='Usuario')),
                ('active', models.BooleanField(default=False)),
                ('Plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.platform', verbose_name='Plataforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('SocialMedia_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.socialmedia', verbose_name='Redes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('Address', models.CharField(max_length=150, verbose_name='Direccion')),
                ('CP', models.PositiveIntegerField(default=0, verbose_name='Codigo postal')),
                ('latitud', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('active', models.BooleanField(default=False)),
                ('Municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.municipality', verbose_name='Municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.state', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='School',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.school', verbose_name='Escuela'),
        ),
    ]
